"""Callbacks for the Timer tool modal — **canonical example** for new tools.

This module defines callbacks that:
- Open/close the modal when the launch button is clicked.
- Populate the duration and Task Name from the example picker.
- Validate the form and enable/disable the submit button.
- Submit a timed job to the backend scheduler.

Callback conventions
--------------------
- Callback **function names start with a verb** describing the action:
  ``toggle_*``, ``populate_*``, ``validate_*``, ``submit_*``.
- All component IDs are f-strings of ``TOOL_DEF["slug"]`` — never
  hardcode slug strings.
- The launch-button ID is auto-generated by ``tool_cards.py`` as
  ``f"id-btn-launch-{TOOL_DEF['slug']}"``.  Match it exactly.
- Always add ``prevent_initial_call=True`` on callbacks that should not
  fire at page load.
- For detailed callback authoring patterns (guard clauses, decorator
  syntax, naming), follow the Write-Callback Agent.
"""

from dash import Input, Output, State, callback, ctx, no_update
from dash.exceptions import PreventUpdate
from flask import g

from enzyme_tk_app.app.backend import get_task_scheduler
from enzyme_tk_app.app.tools.timer_tool_template import TOOL_DEF
from enzyme_tk_app.app.tools.timer_tool_template.modal import _get_example_durations
from enzyme_tk_app.app.utils.submission_limits import validate_active_job_limit

# Build lookup dict: example duration (the dropdown value) -> task name.
# The dropdown hands the callback only the value, so this is how the picker
# recovers the name that goes with it.
_TASK_NAMES_BY_VALUE = {ex["value"]: ex["task_name"] for ex in _get_example_durations()}

# ---------------------------------------------------------------------------
# 1. Toggle modal open / close
# ---------------------------------------------------------------------------


@callback(
    Output(f"id-modal-{TOOL_DEF['slug']}", "is_open"),
    # This ID is created by tool_cards.py: f"id-btn-launch-{slug}"
    Input(f"id-btn-launch-{TOOL_DEF['slug']}", "n_clicks"),
    # This ID is defined in modal.py: f"id-btn-{slug}-cancel"
    Input(f"id-btn-{TOOL_DEF['slug']}-cancel", "n_clicks"),
    prevent_initial_call=True,
)
def toggle_timer_modal(launch_clicks, cancel_clicks):
    """Open or close the Timer modal based on the triggering button.

    The modal opens when the launch button is clicked and closes only via
    the Close button (or the header X).  The Submit button does **not**
    close the modal — so the user can see the returned job ID.

    Args:
        launch_clicks: Number of clicks on the launch button.
        cancel_clicks: Number of clicks on the close button.

    Returns:
        ``True`` to open the modal (launch), ``False`` to close it.
    """
    # ctx.triggered_id tells us which Input fired the callback.
    if ctx.triggered_id == f"id-btn-launch-{TOOL_DEF['slug']}":
        return True
    return False


# ---------------------------------------------------------------------------
# 2. Populate the form from the example picker
# ---------------------------------------------------------------------------


@callback(
    Output(f"id-input-{TOOL_DEF['slug']}-duration", "value"),
    # The Task Name output goes LAST in every populate_example_* callback.
    Output(f"id-input-{TOOL_DEF['slug']}-task-name", "value"),
    Input(f"id-dropdown-{TOOL_DEF['slug']}-example", "value"),
    prevent_initial_call=True,
)
def populate_example_duration(example_value):
    """Populate the duration input and Task Name when an example is selected.

    This is the pattern every tool uses: one selection fills each input the
    example covers, plus the Task Name — the field that blocks submit, so
    filling it is what makes a demo run one click away.  The name carries no
    tool prefix; the My Tasks table already has a Tool column beside Task
    Name.  An already-typed name is overwritten, like every other
    example-filled field.

    Args:
        example_value: The selected example duration in seconds.

    Returns:
        Tuple of (duration, task_name).  The task name is ``no_update`` for a
        duration that is not one of the shipped examples — the user's own name
        is left alone rather than blanked.
    """
    if not example_value:
        raise PreventUpdate

    task_name = _TASK_NAMES_BY_VALUE.get(example_value)
    return example_value, task_name or no_update


# ---------------------------------------------------------------------------
# 3. Validate the form
# ---------------------------------------------------------------------------


@callback(
    Output(f"id-btn-{TOOL_DEF['slug']}-submit", "disabled"),
    Input(f"id-input-{TOOL_DEF['slug']}-task-name", "value"),
    Input(f"id-input-{TOOL_DEF['slug']}-duration", "value"),
    # No prevent_initial_call — this must fire at page load so the Run button
    # starts disabled on an empty form.
)
def validate_timer_form(task_name, duration):
    """Enable the Run button only once every required field has a value.

    Check **presence, not validity**.  ``dbc.Input(type="number", min=1,
    max=300)`` makes the browser mark an out-of-range entry invalid, and Dash
    then hands this callback ``None`` — so 0 or 500 disables the button here
    and never reaches ``submit_timer_job``'s range message.  That message is
    the server-side backstop for a request that bypasses the UI, which is why
    the guard there covers only the task name.

    Args:
        task_name: The current Task Name text.
        duration: The current duration value, or ``None`` when the browser
            rejected what was typed.

    Returns:
        ``True`` to disable the submit button, ``False`` to enable it.
    """
    has_name = task_name and task_name.strip()
    # Deliberately not `bool(duration)` — a bare 0 is present, just out of range.
    has_duration = duration is not None and str(duration).strip() != ""
    return not (has_name and has_duration)


# ---------------------------------------------------------------------------
# 4. Submit job
# ---------------------------------------------------------------------------


@callback(
    # Output to the job-ID / status placeholder div in the modal.
    Output(f"id-div-{TOOL_DEF['slug']}-results", "children"),
    # trigger on the submit button — and also the launch button to clear stale state.
    Input(f"id-btn-{TOOL_DEF['slug']}-submit", "n_clicks"),
    # trigger on the launch button so we can clear stale state.
    Input(f"id-btn-launch-{TOOL_DEF['slug']}", "n_clicks"),
    # input values needed to submit the job — State order mirrors the modal's
    # field order, and so does the params dict built below.
    State(f"id-input-{TOOL_DEF['slug']}-task-name", "value"),
    State(f"id-input-{TOOL_DEF['slug']}-duration", "value"),
    State(f"id-check-{TOOL_DEF['slug']}-fail", "value"),
    prevent_initial_call=True,
)
def submit_timer_job(submit_clicks, launch_clicks, task_name, duration, simulate_failure):
    """Submit a timer job or clear stale results when the modal reopens.

    **Pattern:** Every submit callback should also listen for the
    launch-button click.  When the launch button fires, clear the
    results placeholder so the user does not see a stale job ID from
    a previous submission.

    Args:
        submit_clicks: Number of clicks on the submit button.
        launch_clicks: Number of clicks on the launch button.
        task_name: The user-supplied name for this job.
        duration: The requested duration in seconds.
        simulate_failure: Whether to simulate a mid-run failure.

    Returns:
        A status message with the submitted job ID, or an empty string
        when clearing stale state.
    """
    # ── Clear stale results on modal reopen (intentional DOM write, not a guard) ──
    if ctx.triggered_id == f"id-btn-launch-{TOOL_DEF['slug']}":
        return ""

    # ── Re-validate server-side ─────────────────────────────────────
    # validate_timer_form already disables the button, but a crafted request
    # could bypass it.  This guard covers ONLY task_name — duration has its own
    # validator below that returns a message, and testing it here would swallow
    # that message behind a silent PreventUpdate.
    if not task_name or not task_name.strip():
        raise PreventUpdate

    # ── Validate and clamp duration ─────────────────────────────────
    try:
        seconds = int(duration)
    except (TypeError, ValueError):
        return "Invalid duration — please enter a number between 1 and 300."

    if seconds < 1 or seconds > 300:
        return "Duration must be between 1 and 300 seconds."

    # Last guard, so a malformed submit still shows its own field error first.
    # No-op unless the deployment switched the limit on.
    error = validate_active_job_limit(g.session_id)
    if error:
        return error

    # ── Submit to the backend ───────────────────────────────────────
    # get_task_scheduler() returns the singleton TaskScheduler
    # (Celery in production, in-process in dev).
    scheduler = get_task_scheduler()

    # The ``params`` dict is serialised to JSON and passed verbatim
    # to ``compute.run(params)`` in the Celery worker.  Its keys must
    # match what ``compute.run()`` expects.
    job_id = scheduler.submit_job(
        # Always use TOOL_DEF["slug"] — never a hardcoded string.
        tool_slug=TOOL_DEF["slug"],
        # Key order mirrors the modal's field order — the results page renders
        # the Input Parameters rows in this order, so task_name comes first.
        params={
            "task_name": task_name.strip(),
            "seconds": seconds,
            "simulate_failure": bool(simulate_failure),
        },
        # ``g.session_id`` is the anonymous session UUID from the
        # ``etk_session_id`` cookie, set by ``session.py``.
        session_id=g.session_id,
    )

    fail_note = " (will simulate failure)" if simulate_failure else ""
    return f"Job submitted — ID: {job_id} (will run for {seconds}s{fail_note})"
