"""Callbacks for the Timer tool modal — **canonical example** for new tools.

This module defines callbacks that:
- Open/close the modal when the launch button is clicked.
- Sync the quick-select radio with the number input.
- Submit a timed job to the backend scheduler.

Callback conventions
--------------------
- Callback **function names start with a verb** describing the action:
  ``toggle_*``, ``sync_*``, ``submit_*``.
- All component IDs are f-strings of ``TOOL_DEF["slug"]`` — never
  hardcode slug strings.
- The launch-button ID is auto-generated by ``tool_cards.py`` as
  ``f"id-btn-launch-{TOOL_DEF['slug']}"``.  Match it exactly.
- Use ``raise PreventUpdate`` for early-exit guard clauses instead of
  returning empty strings or ``None``.
- Always add ``prevent_initial_call=True`` on callbacks that should not
  fire at page load.
"""

from dash import Input, Output, State, callback, ctx
from flask import g

from enzyme_tk_app.app.backend import get_task_scheduler
from enzyme_tk_app.app.tools.timer_tool_template import TOOL_DEF

# ---------------------------------------------------------------------------
# 1. Toggle modal open / close
# ---------------------------------------------------------------------------


@callback(
    Output(f"id-modal-{TOOL_DEF['slug']}", "is_open"),
    [
        # This ID is created by tool_cards.py: f"id-btn-launch-{slug}"
        Input(f"id-btn-launch-{TOOL_DEF['slug']}", "n_clicks"),
        # This ID is defined in modal.py: f"id-btn-{slug}-cancel"
        Input(f"id-btn-{TOOL_DEF['slug']}-cancel", "n_clicks"),
    ],
    prevent_initial_call=True,
)
def toggle_timer_modal(launch_clicks, cancel_clicks):
    """Open or close the Timer modal based on the triggering button.

    The modal opens when the launch button is clicked and closes only via
    the Close button (or the header X).  The Submit button does **not**
    close the modal — so the user can see the returned job ID.

    Args:
        launch_clicks: Number of clicks on the launch button.
        cancel_clicks: Number of clicks on the close button.

    Returns:
        ``True`` to open the modal (launch), ``False`` to close it.
    """
    # ctx.triggered_id tells us which Input fired the callback.
    if ctx.triggered_id == f"id-btn-launch-{TOOL_DEF['slug']}":
        return True
    return False


# ---------------------------------------------------------------------------
# 2. Sync quick-select → number input
# ---------------------------------------------------------------------------


@callback(
    Output(f"id-input-{TOOL_DEF['slug']}-duration", "value"),
    Input(f"id-radio-{TOOL_DEF['slug']}-quick", "value"),
    prevent_initial_call=True,
)
def sync_quick_select_to_input(quick_value):
    """Update the duration input when a quick-select radio is chosen.

    This demonstrates a simple two-way sync pattern — one control
    drives another so the user can pick whichever they prefer.

    Args:
        quick_value: The selected quick-select duration in seconds.

    Returns:
        The duration value to set in the number input.
    """
    return quick_value


# ---------------------------------------------------------------------------
# 3. Submit job
# ---------------------------------------------------------------------------


@callback(
    # Output to the job-ID / status placeholder div in the modal.
    Output(f"id-div-{TOOL_DEF['slug']}-results", "children"),
    # trigger on the submit button — and also the launch button to clear stale state.
    Input(f"id-btn-{TOOL_DEF['slug']}-submit", "n_clicks"),
    # trigger on the launch button so we can clear stale state.
    Input(f"id-btn-launch-{TOOL_DEF['slug']}", "n_clicks"),
    # input values needed to submit the job
    State(f"id-input-{TOOL_DEF['slug']}-duration", "value"),
    State(f"id-check-{TOOL_DEF['slug']}-fail", "value"),
    prevent_initial_call=True,
)
def submit_timer_job(submit_clicks, launch_clicks, duration, simulate_failure):
    """Submit a timer job or clear stale results when the modal reopens.

    **Pattern:** Every submit callback should also listen for the
    launch-button click.  When the launch button fires, clear the
    results placeholder so the user does not see a stale job ID from
    a previous submission.

    Args:
        submit_clicks: Number of clicks on the submit button.
        launch_clicks: Number of clicks on the launch button.
        duration: The requested duration in seconds.
        simulate_failure: Whether to simulate a mid-run failure.

    Returns:
        A status message with the submitted job ID, or an empty string
        when clearing stale state.
    """
    # ── Guard: clear stale results on modal reopen ──────────────────
    if ctx.triggered_id == f"id-btn-launch-{TOOL_DEF['slug']}":
        return ""

    # ── Validate and clamp duration ─────────────────────────────────
    try:
        seconds = int(duration)
    except (TypeError, ValueError):
        return "Invalid duration — please enter a number between 1 and 300."

    if seconds < 1 or seconds > 300:
        return "Duration must be between 1 and 300 seconds."

    # ── Submit to the backend ───────────────────────────────────────
    # get_task_scheduler() returns the singleton TaskScheduler
    # (Celery in production, in-process in dev).
    scheduler = get_task_scheduler()

    # The ``params`` dict is serialised to JSON and passed verbatim
    # to ``compute.run(params)`` in the Celery worker.  Its keys must
    # match what ``compute.run()`` expects.
    job_id = scheduler.submit_job(
        # Always use TOOL_DEF["slug"] — never a hardcoded string.
        tool_slug=TOOL_DEF["slug"],
        params={"seconds": seconds, "simulate_failure": bool(simulate_failure)},
        # ``g.session_id`` is the anonymous session UUID from the
        # ``etk_session_id`` cookie, set by ``session.py``.
        session_id=g.session_id,
    )

    fail_note = " (will simulate failure)" if simulate_failure else ""
    return f"Job submitted — ID: {job_id} (will run for {seconds}s{fail_note})"
